"""Add AutoAnalyticalModel

Revision ID: 1124368513f0
Revises: 08611100043c
Create Date: 2026-02-01 05:49:26.194558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1124368513f0'
down_revision = '08611100043c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_analytical_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('vendor_name', sa.String(length=128), nullable=True),
    sa.Column('analytical_account_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_analytical_models')
    # ### end Alembic commands ###
