"""Add_SO_Analytics

Revision ID: 1f66cda30a0a
Revises: a43b94950701
Create Date: 2026-02-01 05:19:05.430443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f66cda30a0a'
down_revision = 'a43b94950701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_analytics', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_order_lines', schema=None) as batch_op:
        batch_op.drop_column('budget_analytics')

    # ### end Alembic commands ###
